name: ProgressBarDemo
options:
  createIntermediateGroups: true
packages:
  ProgressBar:
    path: .
targets:
  iOSDemo:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: iOSDemo
        excludes:
          - iOSDemo.xcodeproj
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.sun.ProgressBarDemo
      INFOPLIST_FILE: iOSDemo/Info.plist
    dependencies:
      - package: ProgressBar
        product: ProgressBar
schemes:
  iOSDemo:
    build:
      targets:
        iOSDemo: all

